services:
  mongo:
    image: mongo:7
    container_name: training_mongodb
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - training_network

  backend:
    build: ./backend
    container_name: training_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/training_db
      - NODE_ENV=development
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - training_network

  frontend:
    build: ./frontend
    container_name: training_frontend
    restart: always
    ports:
      - "3010:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - training_network
    stdin_open: true
    tty: true

networks:
  training_network:
    driver: bridge

volumes:
  mongo_data:
